AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda Function to Compress Json to Zip

Resources:
  MyLambdaFunctionRole:   ### create custom service role for Lambda ###
    Type: AWS::IAM::Role
    Properties:
      RoleName: MyLambdaFunctionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaBasicExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
              - Effect: Allow
                Action:
                  - s3:HeadObject
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource: '*'

#### create lambda function #####
  MyLambdaFunction:   
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.8
      FunctionName: CompressJsonVideos
      Timeout: 10
      Role: !GetAtt MyLambdaFunctionRole.Arn
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: 
              Ref: MyS3Bucket
            Events: s3:ObjectCreated:*

### create s3 bucket for json video files ####
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: jsonvideos

Outputs:
  MyS3BucketOutput:
    Value: !Ref MyS3Bucket
    Export:
      Name: MyS3Bucket          